name: NewTestActions
on: 
  workflow_dispatch:
    inputs:
      target_environment:
        description: Take Input
        type: choice
        options:
          - dev
          - qa
jobs:
  build:
    runs-on: testagent

    steps:
      - name: Checkout Code
        run: |
          echo "running build job"
          echo "printing current workspace"
          echo ${{github.workspace}}

      - name: build code
        id: buildversion
        run: |
          echo "build java code"
          echo "buildid=1.0" >> "$GITHUB_OUTPUT
          echo  "build id is {{ steps.buildversion.outputs.buildid }}"
          
  
  deploy:
    runs-on: testagent
    needs: build
    steps:
      - name: DevDeployment
        if: ${{ inputs.target_environment == 'dev' }}
        run: echo "deploy to dev server"
      - name: QADeployment
        if: ${{ inputs.target_environment == 'qa' }}
        run: echo "deploy to QA server"
      
